"use client";
import { useRef, useState } from "react";
import { Upload, Loader2, CheckCircle2, AlertTriangle, FileText } from "lucide-react";
import type { CatimporterProduct } from "@/lib/catimporter/types/product";
export function CatimporterPanel() {
 const ref=useRef<HTMLInputElement>(null); const [file,setFile]=useState<File|null>(null); const [provider,setProvider]=useState(""); const [loading,setLoading]=useState(false); const [products,setProducts]=useState<CatimporterProduct[]>([]); const [error,setError]=useState("");
 async function run(){ if(!file)return; setLoading(true); setError(""); const fd=new FormData(); fd.append("file",file); fd.append("proveedor",provider); try{const r=await fetch("/api/admin/catimporter/import",{method:"POST",body:fd}); const d=await r.json(); if(!r.ok) throw new Error(d.error); setProducts(d.products);}catch(e){setError(e instanceof Error?e.message:"Error");}finally{setLoading(false)}}
 const review=products.filter(p=>p.requiresReview);
 return <div className="max-w-6xl space-y-6"><div className="rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm"><div className="mb-5"><h2 className="text-lg font-bold text-zinc-900">Catimporter</h2><p className="text-sm text-zinc-500">Importación unificada de PDF, Word y Excel directamente desde el panel administrativo.</p></div><div className="grid gap-4 md:grid-cols-[1fr_220px_auto]"><button onClick={()=>ref.current?.click()} className="flex items-center gap-3 rounded-xl border-2 border-dashed border-zinc-300 p-4 text-left hover:border-indigo-400"><FileText className="h-6 w-6 text-indigo-500"/><span className="truncate text-sm">{file?file.name:"Seleccionar PDF, DOCX o XLSX"}</span></button><input ref={ref} hidden type="file" accept=".pdf,.docx,.xlsx" onChange={e=>setFile(e.target.files?.[0]??null)}/><input value={provider} onChange={e=>setProvider(e.target.value)} placeholder="Proveedor" className="rounded-xl border border-zinc-300 px-3 text-sm"/><button disabled={!file||loading} onClick={run} className="inline-flex items-center justify-center gap-2 rounded-xl bg-indigo-600 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">{loading?<Loader2 className="h-4 w-4 animate-spin"/>:<Upload className="h-4 w-4"/>}{loading?"Analizando":"Analizar"}</button></div>{error&&<p className="mt-4 text-sm text-red-600">{error}</p>}</div>{products.length>0&&<><div className="grid gap-3 md:grid-cols-3"><Stat label="Productos detectados" value={products.length}/><Stat label="Listos / alta confianza" value={products.filter(p=>!p.requiresReview).length}/><Stat label="Requieren revisión" value={review.length} warn/></div><div className="overflow-hidden rounded-2xl border border-zinc-200 bg-white"><div className="border-b px-5 py-4"><h3 className="font-bold">Resultados y cola de revisión</h3></div><div className="divide-y divide-zinc-100">{products.map(p=><div key={p.id} className="flex flex-wrap items-center gap-3 px-5 py-3"><span className="w-24 font-mono text-xs text-zinc-500">{p.internalCode}</span><div className="min-w-[220px] flex-1"><p className="font-medium text-zinc-900">{p.nombre}</p><p className="text-xs text-zinc-500">{p.marca} · {p.categoria} · Ref: {p.supplierCode||"—"}</p></div><span className="font-semibold">${p.precio_costo.toLocaleString("es-CO")}</span><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${p.requiresReview?"bg-amber-100 text-amber-700":"bg-emerald-100 text-emerald-700"}`}>{p.requiresReview?<AlertTriangle className="mr-1 inline h-3.5 w-3.5"/>:<CheckCircle2 className="mr-1 inline h-3.5 w-3.5"/>}{p.confidence}%</span></div>)}</div></div></>}</div>
}
function Stat({label,value,warn}:{label:string;value:number;warn?:boolean}){return <div className="rounded-xl border border-zinc-200 bg-white p-4"><p className={`text-2xl font-black ${warn?"text-amber-600":"text-zinc-900"}`}>{value}</p><p className="text-xs text-zinc-500">{label}</p></div>}
